# MultiPlot options saved by style manager
set ::MultiPlot::Plot0::title "/home/samba/homes/convidat/Desktop/1UBQ/BULID/Energy/autoimd.log POTENTIAL vs TS"
set ::MultiPlot::Plot0::titlefont "Helvetica"
set ::MultiPlot::Plot0::titlefontsize "10"
set ::MultiPlot::Plot0::linewidth "1 1"
set ::MultiPlot::Plot0::linecolor "Skyblue3 red"
set ::MultiPlot::Plot0::radius "2 2"
set ::MultiPlot::Plot0::fillcolor "Skyblue2 red"
set ::MultiPlot::Plot0::marker "none none"
set ::MultiPlot::Plot0::ylabelfont "Helvetica"
set ::MultiPlot::Plot0::ylabelfontsize "10"
set ::MultiPlot::Plot0::xlabelfont "Helvetica"
set ::MultiPlot::Plot0::xlabelfontsize "10"
set ::MultiPlot::Plot0::ylabeltext "E(kcal/mol)"
set ::MultiPlot::Plot0::xlabeltext "TS"
set ::MultiPlot::Plot0::ymin "  -1853.26"
set ::MultiPlot::Plot0::ymax "   187.224"
set ::MultiPlot::Plot0::xmin "         0"
set ::MultiPlot::Plot0::xmax "     18707"
set ::MultiPlot::Plot0::canh "700"
set ::MultiPlot::Plot0::canw "1000"
::MultiPlot::Plot0::plothandle replot
